### ISSUE TITLE
username vs us

### ISSUE THREAD

**Issue by brianberzins** [jmccann/drone-rubygems#4]
I attempted to use thing plugin to publish to an artifactory rubygem repository and ran into a problem with specifying username and password. I wasn't able to successfully upload using those two parameters.

The problem seems to be between the username parameter and the underlying call to dpl. 

specifically: 'username' vs 'user'
https://github.com/drone-plugins/drone-rubygems/blob/master/main.go#L69
https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/rubygems.rb#L8

I was able to reproduce my failure directly, using the dlp gem on my local machine.
`--user=brian` works while `--username=brian` failed.

If you don't think changing main.go to append `--user` instead of `--username`, let me know.

**Comment by tboerger** [comment]
@BrianBerzins thanks for reporting this, the issue will be fixed with https://github.com/drone-plugins/drone-rubygems/pull/5
